services:
  mysql-timesheet:
    image: mysql:latest
    container_name: mysql-timesheet
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "3306:3306"
    volumes:
      - timesheetvol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  timesheet-app:
    build: .
    image: timesheet-nomprenom-classe
    container_name: timesheet-app
    depends_on:
      mysql-timesheet:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-timesheet:3306/${DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegaceLegacyDatetimeCode=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped

volumes:
  timesheetvol:
    name: timesheetvol


